In [1]:
import numpy as np

In [46]:
A = np.array([
    [1,     2,     -3],
    [-3,    -4,    13],
    [2,     1,      5]
])


I = np.array([
    [1,     0,       0],
    [0,     1,       0],
    [0,     0,       1]
])

np.matmul(I, A)

array([[ 1,  2, -3],
       [-3, -4, 13],
       [ 2,  1,  5]])

In [40]:
E1 = np.array([
    [1,     0,       0],
    [3,     1,      0],
    [0,     0,       1]
])

A = np.matmul(E1, A)
A

array([[ 1,  2, -3],
       [ 0,  2,  4],
       [ 2,  1,  5]])

In [47]:
A = np.array([
       [ 1,  2, -3],
       [ 0,  2,  4],
       [ 2,  1,  5]
    ]
)


E2 = np.array([
    [1,     0,       0],
    [0,     1,       0],
    [-2,     0,      1]
])

A = np.matmul(E2, A)
A

array([[ 1,  2, -3],
       [ 0,  2,  4],
       [ 0, -3, 11]])

In [48]:
A = np.array([
       [ 1,  2, -3],
       [ 0,  2,  4],
       [ 0, -3, 11]
       ]
)

E3 = np.array([
       [ 1,  0,    0],
       [ 0,  1,    0],
       [ 0, 3/2,   1]
    ]
)

A = np.matmul(E3, A)
A

array([[ 1.,  2., -3.],
       [ 0.,  2.,  4.],
       [ 0.,  0., 17.]])

In [52]:
E1 = np.array([
    [1,     0,       0],
    [-3,     1,       0],
    [0,     0,       1]
])

E2 = np.array([
    [1,     0,       0],
    [0,     1,       0],
    [2,     0,      1]
])

E3 = np.array([
    [1,     0,      0],
    [0,     1,      0],
    [0,     -3/2,    1]
])




A = np.array([
    [1,     2,     -3],
    [-3,    -4,     13],
    [2,     1,     -5]
])



L = np.array([
    [1,     0,        0],
    [-3,     1,       0],
    [2,     -3/2,     1]
])

U = np.array([
    [1,     2,      -3],
    [0,     2,      4],
    [0,     0,      7]
])

In [54]:
np.matmul(L, U).astype('int')

array([[ 1,  2, -3],
       [-3, -4, 13],
       [ 2,  1, -5]])

In [43]:
# M = np.array([
#     [ 2, 0, 0 ],
#     [ 1, 1, 0 ],
#     [ 0, 0, 0]
# ])


# E = np.array([
#     [1, 0, 0],
#     [0, 1, 0],
#     [0, 0, 1]
# ])



# np.matmul(M, E)