In [ ]:
import numpy as np

# A = [
#     [1,2,1],
#     [3,8,1],
#     [0,4,1]
# ]
# A = np.array(A)

# E = [ 
#     [1,0,0],
#     [-3,1,0],
#     [0,0,1]   
# ]
# E = np.array(E)

# np.matmul(E, A)

In [78]:
A = np.array([
    [200, 100, 4000],
    [100, 100, 3000],
    [0, 0, 0]
])

E = np.array([ 
    [1,0,0],
    [-1,1,0],
    [0,0,1]
])


A = np.matmul(A, E)
A

array([[ 100,  100, 4000],
       [   0,  100, 3000],
       [   0,    0,    0]])

In [52]:
E = np.array([ 
    [1,0,0],
    [-1,1,0],
    [0,0,1]
])

A = np.matmul(E, A)
A

array([[ 100,    0, 1000],
       [   0,  100, 2000],
       [   0,    0,    0]])

In [53]:
E = np.array([ 
    [1/100,0,0],
    [0,1,0],
    [0,0,1]
])

A = np.matmul(E, A)
A.astype('int')

array([[   1,    0,   10],
       [   0,  100, 2000],
       [   0,    0,    0]])

In [54]:
E = np.array([ 
    [1,0,0],
    [0,1/100,0],
    [0,0,1]
])

A = np.matmul(E, A)
A.astype('int')

array([[ 1,  0, 10],
       [ 0,  1, 20],
       [ 0,  0,  0]])

In [56]:
M = [
    [1,2,1],
    [3,8,1],
    [0,4,1]
]
M = np.array(M)

E_ = [ 
    [0,0,1],
    [0,1,0],
    [1,0,0]   
]
E_ = np.array(E_)

np.matmul(E_, M)

array([[0, 4, 1],
       [3, 8, 1],
       [1, 2, 1]])

In [57]:
A

array([[ 1.,  0., 10.],
       [ 0.,  1., 20.],
       [ 0.,  0.,  0.]])

In [86]:
_E = np.array([
    [1,0,0],
    [1,1,0],
    [0,0,1]  
])


U = np.array([
       [ 100,  100, 4000],
       [   0,  100, 3000],
       [   0,    0,    0]
])

np.matmul(_E, U)

array([[ 100,  100, 4000],
       [ 100,  200, 7000],
       [   0,    0,    0]])

In [91]:
A_ = np.array(
    [
        1,2,-3,
        -3,-4,13,
        2,1,-5
    ]
)

L = np.array([
    [1,0,0],
    [-3,1,0],
    [-2, -3/2, 1]
])

U = np.array([
    [1,2,-3],
    [0,2,4],
    [0,0,7]   
])

np.matmul(L,U)

array([[ 1.,  2., -3.],
       [-3., -4., 13.],
       [-2., -7.,  7.]])

In [113]:
A_ = np.array(
    [
        [1,2,3],
        [3,4,13],
        [2,1,5]
    ]
)

L = np.array([
    [1,0,0],
    [-3,1,0],
    [0,0,1]
])

# U = np.array([
#     [1,2,-3],
#     [0,2,4],
#     [0,0,7]   
# ])

# np.matmul(L,U)

np.matmul(L, A_)

array([[ 1,  2,  3],
       [ 0, -2,  4],
       [ 2,  1,  5]])

In [126]:
A_ = np.array([
       [ 1,  2,  3],
       [ 0, -2,  4],
       [ 2,  1,  5]
])

L = np.array([
    [1,0,0],
    [0,1,0],
    [-2,0,1]
])

np.matmul(L, A_)

array([[ 1,  2,  3],
       [ 0, -2,  4],
       [ 0, -3, -1]])

In [130]:
A_ = np.array([
       [ 1,  2,  3],
       [ 0, -2,  4],
       [ 0, -3, -1]
    ]
)


L = np.array([
    [1,0,0],
    [0,1,0],
    [0,-3/2,1]
])

np.matmul(L, A_)


array([[ 1.,  2.,  3.],
       [ 0., -2.,  4.],
       [ 0.,  0., -7.]])

In [134]:
L = np.array([
    [1,0,0],
    [3,1,0],
    [-2,-3/2,1]
])

U = np.array([
       [ 1,  2,  3],
       [ 0, -2,  4],
       [ 0,  0, -7]
    ]
)

np.matmul(L, U)


array([[ 1.,  2.,  3.],
       [ 3.,  4., 13.],
       [-2., -1., -5.]])