In [ ]:
import numpy as np
from scipy.linalg import orth
import math

In [ ]:
A = np.array([
  [10, 2],
  [5, 11]
])

### SVD (Manual)

In [ ]:
A = np.array([
  [10, 2],
  [5, 11]
])

print(A)
print(A.T)

[[10  2]
 [ 5 11]]
[[10  5]
 [ 2 11]]


In [ ]:
# Step 1
AtA = np.matmul(A, A.T)

In [ ]:
# Step 2
AAt = np.matmul(A.T, A)

In [ ]:
# Step 3
print(np.linalg.eigvals(AtA))
print(np.linalg.eigvals(AAt))

sigma_1 = math.sqrt(np.linalg.eigvals(AAt)[0])
sigma_2 = math.sqrt(np.linalg.eigvals(AAt)[1])


print('sigma_1', sigma_1)
print('sigma_2', sigma_2)

[ 50. 200.]
[200.  50.]
sigma_1 14.142135623730951
sigma_2 7.071067811865476


In [ ]:
# Step 4
S = np.array([
    [sigma_1, 0],
    [0, sigma_2]
])

In [ ]:
# Step 5
# See Gram Schmidt algorithm, https://media.cheggcdn.com/media%2Ffa3%2Ffa3fb1ca-e6d4-469d-8691-58dc5624d7cf%2FphpEAj5dG.png
U = orth(AtA)
print(U)

[[-0.6 -0.8]
 [-0.8  0.6]]


In [ ]:
# Step 6
V = orth(AAt)
print(V)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
np.matmul(np.matmul(U,S), V)

array([[10.,  2.],
       [ 5., 11.]])

### SVD Method of NumPy 

In [ ]:
U, S, V = np.linalg.svd(A)

In [ ]:
print(U)
print(S)
print(V)

[[-0.6 -0.8]
 [-0.8  0.6]]
[14.14213562  7.07106781]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
S = np.array([
    [sigma_1, 0],
    [0, sigma_2]
])

In [ ]:
np.matmul(np.matmul(U,S), V)

array([[10.,  2.],
       [ 5., 11.]])